name: tashkentsupermarket
description: Tashkent Supermarket mobile application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.0.2
  path: ^1.6.4
  intl: ^0.16.0
  share: ^0.6.3+5
  http: ^0.12.0+2
  convert: ^2.1.1
  timeago: ^2.0.21
  validate: ^1.7.0
  location: ^2.3.5
  koukicons: ^2.0.1
  uni_links: ^0.2.0
  app_review: ^1.0.0
  provider: ^3.1.0+1
  vector_math: ^2.0.8
  device_apps: ^1.0.8
  rate_my_app: ^0.4.0
  carousel_pro: ^1.0.0
  place_picker: ^0.9.9
  url_launcher: ^5.2.5
  fluttertoast: ^3.1.3
  firestore_ui: ^1.7.2
  random_string: ^1.1.0
  localstorage: ^3.0.0+3
  page_indicator: ^0.3.0
  flutter_swiper: ^1.1.6
  auto_size_text: ^2.1.0
  connectivity: ^0.4.5+3
  extended_image: ^0.6.8
  after_layout: ^1.0.7+2
  html_unescape: ^1.0.1+3
  country_pickers: ^1.1.0
  pull_to_refresh: ^1.5.7
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+11
  firebase_core: ^0.4.3+1
  firebase_auth: ^0.14.0+8
  firebase_storage: ^3.0.8
  flutter_widgets: ^0.1.7+1
  fab_circular_menu: ^0.1.1
  transparent_image: ^1.0.0
  cloud_firestore: ^0.12.10
  flutter_screenutil: ^0.6.0
  firebase_messaging: ^5.1.8
  firebase_analytics: ^5.0.9
  flutter_account_kit: ^0.7.0
  flare_splash_screen: ^3.0.0
  flutter_credit_card: ^0.1.3
  lazy_load_scrollview: ^1.0.1
  flutter_range_slider: ^1.4.0
  cached_network_image: 2.0.0-rc
  shared_preferences: ^0.5.4+5
  font_awesome_flutter: ^8.5.0
  intro_views_flutter: '^2.8.0'
  flutter_signin_button: ^1.0.0
  flutter_webview_plugin: ^0.3.9+1
  flutter_facebook_login: ^3.0.0
  google_maps_flutter: ^0.5.21+12
  notification_permissions: ^0.4.3
  configurable_expansion_tile: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_widget_from_html_core: ^0.2.4+3

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:

  uses-material-design: true
  assets:
    - lib/common/config.json
    - assets/icons/payment/
    - assets/icons/profile/
    - assets/icons/tabs/
    - assets/images/intro/
    - assets/images/
    - assets/splashscreen.flr

  fonts:
    - family: MyFont
      fonts:
      - asset: assets/fonts/sspu.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
